// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm53H7Ly5eywKvKTpcI57ZQHmhRCoK8A8',
    appId: '1:202804853993:web:ca6ac4c01539add1dc8478',
    messagingSenderId: '202804853993',
    projectId: 'sign-lang-app',
    authDomain: 'sign-lang-app.firebaseapp.com',
    storageBucket: 'sign-lang-app.appspot.com',
    measurementId: 'G-0BJ3NEV89J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGunL0Of5ouU66j5fgJYQudrGczwdkZ4',
    appId: '1:202804853993:android:4eae14165e9a877adc8478',
    messagingSenderId: '202804853993',
    projectId: 'sign-lang-app',
    storageBucket: 'sign-lang-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeUqVYYUDPH4MegZ0zLBOWcUYOj2IH48',
    appId: '1:202804853993:ios:22fd980a5ad67f69dc8478',
    messagingSenderId: '202804853993',
    projectId: 'sign-lang-app',
    storageBucket: 'sign-lang-app.appspot.com',
    iosBundleId: 'com.example.signLangApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGeUqVYYUDPH4MegZ0zLBOWcUYOj2IH48',
    appId: '1:202804853993:ios:903dd63b209d5751dc8478',
    messagingSenderId: '202804853993',
    projectId: 'sign-lang-app',
    storageBucket: 'sign-lang-app.appspot.com',
    iosBundleId: 'com.example.signLangApp.RunnerTests',
  );
}
